source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

# Core Rails
gem 'rails', '~> 8.0.0'
gem 'puma', '~> 6.0'
gem 'bootsnap', '>= 1.4.4', require: false

# Database
gem 'pg', '~> 1.5'

# API
gem 'rack-cors'
gem 'jbuilder', '~> 2.11'
gem 'active_model_serializers'

# Authentication
gem 'jwt'
gem 'bcrypt', '~> 3.1.7'
gem 'omniauth'
gem 'omniauth-google-oauth2'   
gem 'omniauth-facebook'

# Email
gem 'mail'

# Utilities
gem 'dotenv-rails'
gem 'uuid'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end
